# NUMPY

### Importamos la librería

In [2]:
import numpy as np

### Básico

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [36]:
b = np.array([[6.0,7.0,8.0],[3.0,4.0,5.0]])
print(b)

[[6. 7. 8.]
 [3. 4. 5.]]


In [8]:
c = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,20,30],[40,50,60],[70,80,90]],[[100,200,300],[400,500,600],[700,800,900]]])
print(c)

[[[  1   2   3]
  [  4   5   6]
  [  7   8   9]]

 [[ 10  20  30]
  [ 40  50  60]
  [ 70  80  90]]

 [[100 200 300]
  [400 500 600]
  [700 800 900]]]


### Dimensión de la matríz

In [14]:
print(a.ndim)
print(a.shape)

1
(3,)


In [15]:
print(b.ndim)
print(b.shape) # filas - columnas

2
(2, 3)


In [16]:
print (c.ndim)
print(c.shape) # filas - columnas - profundidad

3
(3, 3, 3)


### Tipo de la matríz

In [17]:
a.dtype

dtype('int64')

In [18]:
b.dtype

dtype('float64')

In [20]:
a = np.array([1,2,3],dtype = 'int16')

In [21]:
a.dtype

dtype('int16')

In [31]:
b.dtype

dtype('float64')

In [22]:
print(a)

[1 2 3]


### Tamaño de la matríz

In [23]:
a.itemsize #Cantidad de bytes que ocupa cada item para int16 = 2 para int 32 = 4 ... etc

2

In [24]:
a.size

3

In [25]:
b.size # 3 columas, 2 filas

6

In [26]:
c.size # 3 col, 3 filas y 3 profundidad

27

In [27]:
a.nbytes # cantidad de bytes totales que ocupa la matriz en memoria

6

In [37]:
print(b.nbytes)
print(b.dtype)

48
float64


In [29]:
c.nbytes

216

In [38]:
b = np.array([[6.0,7.0,8.0],[3.0,4.0,5.0]],dtype = 'float16')
b.nbytes # Al cambiar el timpo de matriz a float16 ahorramos espacio en memoria innecesario
# Esto hace el proceso y la operación con matrices mucho más rapida

12

## Acceso, cambiar elementos, filas, columnas y más

In [40]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [42]:
b.shape

(3, 3)

### Obtener un elemento de la matríz [fila,columna] o vector [posición]

In [43]:
# Debemos tener en cuenta que el índice comienza en 0
# Tambien tener en cuenta que podemos usar indice negativo siendo el último -1, penúltimo -2, etc...
# por lo tanto:
# Para obtener 1 haremos:
b[0,0]

1

In [45]:
# Entonces para obtener el 7 haremos:
b[2,0]

7

In [48]:
# Con índices negativos para obtener el 7 haremos
print(b[-1,0])
# o tambien podemos usar:
print(b[-1,-3])
# en ambos casos obtenemos el 7
# aunque para mejor entendimiento no es tan recomendable esta practica

7
7


### Obtener una determinada fila o columna de la matriz

In [49]:
# Para obtener una fila determinada de la matríz
# en este caso será la fila 2
b[1,:]

array([4, 5, 6])

In [50]:
# Para obtener una columna determinada de la matríz
# en este caso será la columna 1
b[:,0]

array([1, 4, 7])

In [56]:
# Para recorrer cierta cantidad de elementos en una fila usaremos
# indicecomienzo:indicefinal+1(Como es un rango siempre es 1 menos):paso(opcional)
# Por ejemplo para tomar el 1 y el 3 de la fila 1 haremos
b[0,0:3:2]

array([1, 3])

In [57]:
# Para obtener las esquinas (1.1,1.3,3.1 y 3.3) de una matriz 3x3 haremos
b[0:3:2,0:3:2] # siendo n el numero de filas y m el numero de columnas
# esta formula para obtener las esquinas es [0:n:n-1,0:m:m-1]

array([[1, 3],
       [7, 9]])

### Cambiar un elemento específico en una matríz

In [60]:
# Para cambiar un elemento específico 
# primero lo "llamamos" como lo haríamos
# luego le realizamos la nueva asignación (todo en la misma linea)
# de esta forma:
b[0,0] = 10 # recordemos qu es 1, pero lo cambiamos a 10
# Si mostramos b, veremos el cambio
print(b)

[[10  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [61]:
# Para cambiar una serie de números usamos la misma lógica
# "Llamamos" y luego asignamos
# Por ejemplo para cambiar la fila 1 podemos realizar:
b[0,:]=[10,20,30]
print(b) # mostramos la matríz para ver el cambio

[[10 20 30]
 [ 4  5  6]
 [ 7  8  9]]


In [62]:
# Podemos hacer lo mismo asignando a todos un mismo valor
# en este caso pondremos todos 2 en la columna 2
b[:,1] = 2
print(b)

[[10  2 30]
 [ 4  2  6]
 [ 7  2  9]]


In [64]:
# Para los tensores de 3 dimensiones (incorporan profundidad o capas), ocurre igual
# en caso de tener un tensor 3d, debemos agregar una coordenada más que indique la "capa"
# entonces primero declararemos un tensor 3d y luego ejecutaremos algunas operaciones
a3d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a3d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [65]:
# Entonces para las operaciones de obtener o cambiar elementos especificos agregamos la coordenada de "capa"
# Por ejemplo para obtener el número 6 haremos
a3d[1,0,1]

6

In [74]:
# Para cambiar elementos realizamos lo mismo, tambien agregando la nueva coordenada
# Por ejemplo a la "capa" 1 le cambiaremos los valores a 10,20,30 y 40 respectivamente
a3d[0,:,:]=[[10,20],[30,40]] # Cambiamos la capa completa
print(a3d) # Mostramos la matríz para ver los cambios

[[[10 20]
  [30 40]]

 [[10 14]
  [ 7  8]]]


In [77]:
# Haremos un ejemplo cambiando la primera columna de la segunda capa
# a [5,7] le asignaremos 10 y 14 respectivamente
a3d[1,:,0] = [10,14]
print(a3d)

[[[10 20]
  [30 40]]

 [[10  6]
  [14  8]]]


#### Entonces sabemos que para recorrer una matríz 3D el orden es [capa,fila,columna]

## Iniciar Matrices Específicas

In [88]:
# Matríz con todos 0s - funcion np.zeros(forma)
print(np.zeros(3),"vector \n") # vector longitud = 3
print(np.zeros((3,3)),"matríz \n") # Matríz nm = 3x3
print(np.zeros((3,3,3)),"tensor 3d") # Tensor 3d = 3x3x3

[0. 0. 0.] vector 

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] matríz 

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]] tensor 3d


In [89]:
# Matríz con todos 1s - funcion np.ones(forma)
print(np.ones(2),"vector \n") # vector longitud = 2
print(np.zeros((2,2)),"matríz \n") # Matríz nm = 2x2
print(np.zeros((2,2,2)),"tensor 3d") # Tensor 3d = 2x2x2

[1. 1.] vector 

[[0. 0.]
 [0. 0.]] matríz 

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]] tensor 3d


In [90]:
# Matríz con un número distinto de 0 y 1 - funcion np.full(forma,número)
print(np.full(4,7),"vector \n") # 4 columnas
print(np.full((4,4),7),"matríz \n") # 4 fil, 4 col
print(np.full((3,2,4),7),"tensor 3d") # 3 capas, 2 filas, 4 col

[7 7 7 7] vector 

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]] matríz 

[[[7 7 7 7]
  [7 7 7 7]]

 [[7 7 7 7]
  [7 7 7 7]]

 [[7 7 7 7]
  [7 7 7 7]]] tensor 3d


In [91]:
# Podemos utilizar la forma de otra matríz en el argumento forma
# por ejemplo esta vez usaremos la forma de la matríz a3d anteriormente utilizada
np.full(a3d.shape,12)

array([[[12, 12],
        [12, 12]],

       [[12, 12],
        [12, 12]]])

In [92]:
# lo mismo podemos hacer utilizando otra funcion la cual es np.full_like(matriz_a_copiar,número)
# Realizaremos el mismo ejemplo pero con esta función
np.full_like(a3d,12)

array([[[12, 12],
        [12, 12]],

       [[12, 12],
        [12, 12]]])

In [93]:
# Matriz de numeros decimales aleatorios entre 0 y 1 - función np.random.rand(forma)
np.random.rand(4,2)

array([[0.37989992, 0.65348895],
       [0.17026242, 0.98247786],
       [0.1757197 , 0.27257117],
       [0.61629988, 0.07327805]])

In [95]:
# Para realizar la misma matríz aleatoria pero pasarle la forma de otra usamos la función
# np.random.random_sample(forma) , usaremos la forma de a3d para el ejemplo
np.random.random_sample(a3d.shape)

array([[[0.35433151, 0.23892235],
        [0.35979473, 0.18303805]],

       [[0.22801053, 0.38085872],
        [0.37303217, 0.04735189]]])

In [96]:
# Matríz aleatoría de enteros - función np.random.randint(inicio[default = 0],final+1,size[default = 1])
np.random.randint(4) # Escalar aleatorio entre 0 y 4

1

In [97]:
np.random.randint(5,13) # Escalar aleatorio entre 5 y 13

11

In [98]:
np.random.randint(0,10,size = (3,3)) # Matríz 3x3 de aleatorios entre 0 y 10

array([[0, 5, 4],
       [6, 6, 5],
       [6, 2, 3]])

In [102]:
np.random.randint(2,size = (3,3)) # Matríz 3x3 booleana aleatoria

array([[1, 0, 0],
       [1, 0, 1],
       [0, 1, 0]])

In [108]:
# Estas pueden tomar como parametro números negativos, por ejemplo
np.random.randint(-3,4,size = (3,3,3)) # Matríz 3x3x3 de num aleatorios entre -3 y 3

array([[[-1,  2,  1],
        [-2,  1,  0],
        [ 3, -2,  0]],

       [[ 1, -2,  0],
        [-2, -3,  1],
        [ 2, -1,  0]],

       [[ 0,  1, -1],
        [ 2, -3,  2],
        [-3, -2, -2]]])

In [110]:
# Matriz identidad - función np.identity(tamaño)
# Por defecto las matrices identidad son cuadradas por lo que el tamaño ingresado = t
# Dará como resultado una matriz donde filas = t y columnas = t y tiene 1s en la diagonal principal, por ejemplo
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [118]:
# Para repetir matrices n veces - función np.repeat(matríz,repeticiones,eje de repeticiones[default = 1 = x;0 = y])
# Se le pasa como argumento una matríz y la cantidad de repeticiones requeridas
arr = np.array([1,2,3])
rep = np.repeat(arr,5) # Generamos 5 1s, 5 2s, ...
# Si queremos que se repitan en el eje "y" debemos crear una matriz, no un vector, y aclarar en el repeat el eje y
arr2 = np.array([[4,5,6]])
rep2 = np.repeat(arr2,3,axis = 0)
print(arr)
print(arr2)
print(rep)
print(rep2)

[1 2 3]
[[4 5 6]]
[1 1 1 1 1 2 2 2 2 2 3 3 3 3 3]
[[4 5 6]
 [4 5 6]
 [4 5 6]]


In [156]:
# Para generar una matríz diagonal - función np.diag(tamaño)
# daremos un ejemplo
diag = np.diag((1,1,1)) # Construimos la matríz poniendo los elementos que van en la diagonal
print(diag)

# Para generar una matríz de elementos en el triangulo superior de la matríz
print(np.triu((1,3,1))) # Indicamos los números que queremos en las columnas que formen el triang superior

print(np.tril((2,1,2))) # Nuevamente indicamos los números que queremos en las col que forman el triang inferior

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 3 1]
 [0 3 1]
 [0 0 1]]
[[2 0 0]
 [2 1 0]
 [2 1 2]]


In [157]:
# Para generar una matríz o vector con un rango entre números - np.arange(desde,hasta,paso)
pares = np.arange(2,51,2) # Generamos a partir del 2 hasta el 50 con paso 2 (pares hasta el 50)
print(pares)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]


In [170]:
# Para generar una matríz a partir de una cadena de caracteres - np.char.array(cadena)
saludo = np.char.array(['hola,','como','estás?'])
print(saludo)

['hola,' 'como' 'estás?']


In [ ]:
# Existen más iniciaciones de matrices más específicas
# En caso de interesarte, dejaré un link en la página principal del repo

### Problema 1 : Generar la matríz [[1,1,1,1,1],[1,0,0,0,1],[1,0,9,0,1],[1,0,0,0,1],[1,1,1,1,1]]

In [119]:
# Imprimimos la matríz a generar
problema = np.array([[1,1,1,1,1],[1,0,0,0,1],[1,0,9,0,1],[1,0,0,0,1],[1,1,1,1,1]])
print(problema)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [121]:
# Como vemos esta matríz es de tamaño 5 y es cuadrada ya que cant filas = cant columnas
# Para comenzar crearemos una matríz de 0s de tamaño (5,5)
rta = np.zeros((5,5),dtype = 'int16')
print(rta) # Empezamos de esta forma

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [122]:
# Luego haremos la primer y última fila de 1s
rta[0:5:4,:] = 1
print(rta) # Nos quedaría de esta forma

[[1 1 1 1 1]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [1 1 1 1 1]]


In [123]:
# Ahora convertiremos en 1s la primer y ultima columna con el proceso "inverso"
rta[:,0:5:4] = 1
print(rta) # Ya nos acercamos al final

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [124]:
# Por último debemos cambiar el centro por 9, lo haremos de esta forma
rta[2,2] = 9
print(rta) # Esta es nuestra respuesta final

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### Otra forma de hacerlo

In [125]:
# Otra forma es 1 - crear una matríz de 1s de tamaño 5x5
# Luego 2 - creamos otra matríz de 0s de tamaño 3x3
# A la segunda matríz le 3 - cambiamos el centro por 9
# Por último 4 - asignamos a los lugares correspondientes de la matríz 5x5, la matríz 3x3
rta = np.ones((5,5)) # 1
print(rta)
cambio = np.zeros((3,3)) # 2
print(cambio)
cambio[1,1] = 9 # 3
print(cambio)
rta[1:4,1:4] = cambio # 4
print(rta) # Así quedaría terminada nuestra matríz


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Ten cuidado al copiar Matrices

In [3]:
# Si creamos una matríz a cualquiera, y queremos copiar la misma matríz en una variable x, funcionará
# El problema está que si editamos cualquier elemento de x tambien se cambiará en a, de la siguiente forma
a = np.array([1,2,3])
x = a
x[0] = 10 # Cambiamos el 1 de la matríz x por 10
# ¿Qué crees que pasará cuando imprimamos a y x?
print(a)
print(x)
# Adivinaste, en a tambien se cambió el valor
# Esto ocurre ya que tu le asignaste que uno será igual a la otra con x = a, entonces
# Para cualquier cambio que ocurra en alguna de las dos, se hará tambien en la otra. (Son la misma matríz)

[10  2  3]
[10  2  3]


In [4]:
# Si queremos hacer una copia sin que x sea la misma matríz que a, es decir
# si editamos x no editaremos a y viceversa
# usaremos la función .copy(), por ejemplo
a = np.array([1,2,3]) # Creamos una matríz normalmente
x = a.copy() # Creamos una copia
x[0] = 10 # Cambiamos lo que queramos de x
#Imprimimos por pantalla para ver el resultado de ambas
print(a)
print(x)

[1 2 3]
[10  2  3]


## Matemáticas con Numpy

### Operaciones Básicas

In [5]:
# Uno de los usos más grandes de Numpy es en las matemáticas
# En esta sección introduciremos algunos conceptos

In [70]:
# Podemos operar entre matrices y escalares, para ello...
a = np.array([1,2,3,4])
print(a)
a += 2 # Por cada elemento le sumamos 2
print(a)

[1 2 3 4]
[3 4 5 6]


In [71]:
# De la misma forma podemos restar, a continuación por cada elemento restaremos 3
a -= 3
print(a)

[0 1 2 3]


In [72]:
# A continuación veremos que tambien se puede multiplicar a cada elemento por un escalar
# En el ejemplo multiplicaremos cada elemento por 5
a = a*5
print(a)
# Como vemos en estos casos estamos modificando la matríz
# En caso de querer practicar las operaciones sin modificarlas podemos hacer
# print(a*2) o print(a-4), etc etc

[ 0  5 10 15]


In [73]:
# De la misma forma podemos dividir cada elemento entre un escalar
# En este ejemplo dividiremos por 2
a = a/2
print(a)
# Esto nos devolverá una matríz de numeros decimales ya que la división no es exacta

[0.  2.5 5.  7.5]


In [74]:
# Tambien podremos sumar matrices siempre que estas tengan el mismo tamaño
# Por ejemplo al actual valor en a le sumaremos una nueva matríz b
b = np.array([10,2.5,0,2.5])
c = a+b # Creamos una nueva matríz que guarde el valor de la suma entre a y b
print(a)
print(b)
print(c)

[0.  2.5 5.  7.5]
[10.   2.5  0.   2.5]
[10.  5.  5. 10.]


In [79]:
# Otra operación que podremos realizar es elevar cada elemento de la matríz por un número
# en este ejemplo elevaremos c al cuadrado
print (c**2)
# Tambien existe una función para elevar cada elemento a un número, la misma es np.exp
print(np.power(c,2)) # Tambien podremos elevar una matríz por otra

[100.  25.  25. 100.]
[100.  25.  25. 100.]


In [98]:
# Podemos calcular la sumatoria y la multiplicación de los elementos del vector con la funcion
# Los mismos se pueden calcular como la sumatoria por fila (axis = 1) o sumatoria por columnas (axis = 0)
# Para ello utilizaremos las siguientes funciones
a = np.array([[2,4,6,8]])
a2d = a.repeat(3,axis = 0)
print(a)
print(a2d)
print(a.sum())
print(a2d.sum(axis = 0))
print(a.prod())
print(a2d.prod(axis = 0))

[[2 4 6 8]]
[[2 4 6 8]
 [2 4 6 8]
 [2 4 6 8]]
20
[ 6 12 18 24]
384
[  8  64 216 512]


### Funciones Trigonometricas

In [61]:
# Tambien por ejemplo podemos realizar el seno, el coseno y la tangente de cada elemento de una matríz
# acá vemos un ejemplo
rad = np.array([1,2,3,4])
print(np.sin(rad))
print(np.cos(rad))
print(np.tan(rad))
# Tanto seno, coseno y tang de una matríz se pueden realizar con respectivas funciones
# Las funciones anteriores utilizan como unidad los radianes
# Para convertirlo de radianes a grados usaremos la función np.degrees(matríz/vector/etc)
print(np.degrees(rad)) # Nos mostrára cuantos grados son los elementos que le pasemos

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128]
[ 57.29577951 114.59155903 171.88733854 229.18311805]


In [62]:
# Tambien conociendo los dos catetos de un triángulo rectángulo, podemos calcular la hipotenusa
# Esto lo haremos con la función np.hypot(cat1,cat2), por ejemplo
cat = np.array([20,12]) 
# Suponiendo que tenemos 20 y 12 mts de cateto, calcularemos la hipotenusa
np.hypot(cat[0],cat[1])

23.323807579381203

In [67]:
# Suponiendo que conocemos 2 de las 3 componentes de un ángulo
# Podremos encontrar el ángulo conformado entre ellos
# Para ello usaremos arcsen,arccos o arctan según que partes del triángulo tengamos
# Supongamos que tenemos la hipotenusa y el cateto adyacente, obtendremos alfa de la sig forma:
# Recuerden la "Regla" SOH - CAH - TOA que indica para los datos que tengamos que función utilizar
# En nuestro caso tenemos adyacente e hipotenusa, por ello usaremos el Coseno, entonces
datos = np.array([20,23]) # Declaramos adyac e hipotenusa respectivamente
alfa = np.arccos(datos[0]/datos[1])
print(np.degrees(alfa)) # Imprimimos alfa en grados

29.591845793950736


### Redondeo, Truncamiento y otras

In [112]:
# Para realizar truncamientos, redondeos y demas utilizaremos las funciones
a = np.array([1.394,3.666,5.788])
print(np.trunc(a)) # Devuelve solo el número entero
print(np.around(a,2)) # Devuelve los números redondeados a la cifra que indiquemos
print(np.round(a,1))
print(np.floor(a)) # Devuelve el número entero menor más cercano
print(np.ceil(a)) # Devuelve el número entero mayor más cercano
print(np.fix(a)) # Devuelve el número entero más cercano (depende si los decimales son mayores o menores a 0.5)

[1. 3. 5.]
[1.39 3.67 5.79]
[1.4 3.7 5.8]
[1. 3. 5.]
[2. 4. 6.]
[1. 3. 5.]


In [117]:
# Para encontrar el mcm y dcm de dos números usaremos las funciones
# DCM - función np.gcd(x1,x2)
# mcm - función np.lcm(x1,x2)
print(np.gcd(8,20)) # Máximo común divisor entre 8 y 20 = 4
print(np.lcm(8,18)) # Mínimo comun múltiplo entre 8 y 18 = 72

4
72


In [22]:
# Hay más funciones, no las trabajaremos en esta introducción
# si te interesan te las dejo en la pagina principal del repo

## Álgebra lineal con Numpy

In [184]:
# Para realizar el producto punto entre dos vectores- función np.vdot(vect1,vect2)
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(a)
print(b)
print(np.vdot(a,b)) # realiza (a[0]*b[0])+(a[1]*b[1])+....(a[n]*b[n])

# Para realizar el producto punto entre dos matrices - función np.dot(matríz1,matríz2)
amat = np.array([[1,2],[3,4]])
bmat = np.array([[5,6],[7,8]])
print(amat)
print(bmat)
print(np.dot(amat,bmat),"\n") # Realiza para c[1,1] = a[1,1] * b[1,1] + a[1,2] * b[2,1], igual para el resto

# Para realizar el producto escalar entre dos matrices - función np.inner(matríz1,matríz2)
print(np.inner(amat,bmat))

# Para realizar el producto escalar entre dos vectores - función np.outer(vect1,vect2)
print(np.outer(a,b)) 
# Realiza a[0]*b, a[1]*b, a[2]*b, a[3]*b .. Forma una matriz con los elementos de a como escalares y las filas de b

[1 2 3 4]
[5 6 7 8]
70
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]] 

[[17 23]
 [39 53]]
[[ 5  6  7  8]
 [10 12 14 16]
 [15 18 21 24]
 [20 24 28 32]]


In [35]:
# Recordemos que para multiplicar matrices, debemos de tener una matríz a n.m y b n.m
# de modo tal que la cant de col de a sea igual a la cant de filas de b 
# y que las filas de a y las columnas de b determinarán su tamaño, para ello
# usaremos la función np.matmul(matríz1,matríz2)
a = np.identity(3,dtype="int16") # Matriz a = identidad 3x3(1s en la diagonal principal)
print(a)

b = np.full((3,3),5) # Matríz b = Matríz 3x3 completa con 5
print (b)

print(np.matmul(a,b)) # Producto entre la matríz a y la matríz b, nueva matríz 3x3
# Vease el producto entre matrices en https://es.wikipedia.org/wiki/Multiplicaci%C3%B3n_de_matrices

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[5 5 5]
 [5 5 5]
 [5 5 5]]
[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [37]:
# Para buscar el Determinante de una matríz debemos de recordar que la matríz debe de ser cuadrada
# El Determinante indicará el número de soluciones de los respectivos sistemas de ecuaciones lineales
a = np.array([[1,1],[2,1]])
print(a)
print(np.linalg.det(a)) # Determinante de a que es lo mismo que
# la diferencia entre la mult de los elementos de la diag principal y la mult de los elementos de la diag secundaria
# queda conformada una x en la matriz, por ejemplo para este caso es [1*1]-[1*2] que nos dará como resultado -1

[[1 1]
 [2 1]]
-1.0


In [189]:
# Existe más información y más funciones aplicables al álgebra lineal
# Para saber más puedes visitar la página que dejaré en el repo

### Estadísticas con Numpy

In [195]:
# Podemos obtener el mínimo de una matríz - Función np.min(matríz)
estadisticas = np.array ([[1,2,3],[4,5,6],[7,8,9]])
print(estadisticas)

minimo = np.min(estadisticas)
print(minimo)

# Tambien podremos obtener el máximo de una matríz - Función np.max(matríz)
maximo = np.max(estadisticas)
print(maximo)

# Esos serían los mínimos y máximos de toda la matríz pero que pasa si queremos obtenerlos por filas o columnas?
# Debemos agregar el parametro axis en la función np.max(), por ejemplo
print(np.min(estadisticas,axis = 0)) # Por columna obtenemos que los menores son 1 2 y 3
print(np.min(estadisticas,axis = 1)) # Por fila obtenemos que los menores son 1 4 y 7

print(np.max(estadisticas,axis = 0)) # Por columna obtenemos que los más grandes son 7 8 y 9
print(np.max(estadisticas,axis = 1)) # Por fila obtenemos que los más grandes son 3 6 y 9

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
9
[1 2 3]
[1 4 7]
[7 8 9]
[3 6 9]


### Reorganizar Matrices

In [197]:
# Para cambiarle la forma a una matríz - Función np.reshape(matríz,(cantfilas,cantcol)) o nombmatriz.reshape(forma)
antes = np.array ([[1,2],[3,4],[5,6],[7,8]])
despues = np.reshape(antes,(2,4)) # Generamos una matríz 2x4 con la Forma 1 
despues2 = antes.reshape(2,2,2) # Generamos una matríz 3d con la Forma 2

# Recordemos que debemos de obtener con el reshape la misma cantidad de elementos que la forma original
# De lo contrario obtendremos un error que indica que son menos o más elementos de lo que posee la matríz original

print(antes)
print(despues)
print(despues2)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [200]:
# Para apilar vectores de forma vertical - Función np.vstack([v1,v2,v3,...]) * Orden de arriba hacia abajo
vect1 = np.array([1,2,3])
vect2 = np.array([4,5,6])

print(np.vstack([vect1,vect2])) # Quedará arriba 1,2,3 y debajo 4,5,6
print(np.vstack([vect2,vect1])) # Quedará arriba 4,5,6 y debajo 1,2,3

# Recordemos que los vectores que stackeemos deben de tener el mismo largo
# Podemos stackear cuantos vectores queramos, por ejemplo

print(np.vstack([vect1,vect2,vect2,vect1]))

[[1 2 3]
 [4 5 6]]
[[4 5 6]
 [1 2 3]]
[[1 2 3]
 [4 5 6]
 [4 5 6]
 [1 2 3]]


In [205]:
# Para stackear vectores de forma horizontal - Función np.hstack([v1,v2,v3,....]) * Orden de izquierda a derecha
vect1 = np.array([1,2,3])
vect2 = np.array([4,5,6])
vect3 = np.array([7,8,9])

# En este caso no necesitamos que los vectores a stackear horizontalmente sean del mismo tamaño

print(np.hstack([vect1,vect2,vect3]))
print(np.hstack([vect3,vect2,vect2,vect1]))

[1 2 3 4 5 6 7 8 9]
[7 8 9 4 5 6 4 5 6 1 2 3]


## Otras cosas interesantes Numpy

### Leer datos de un archivo

In [215]:
# En caso de no utilizar pandas para leer archivos, podemos trabajar tambien con numpy
# Para ello necesitaremos obviamente un archivo de texto de donde leer datos
# En nuestro caso estará en el repositorio y se llama data.txt
# En este caso generaremos de un txt y la función a utilizar es np.genfromtxt(nombredelarchivo,delimitador,dtype)
data = np.genfromtxt('data.txt',delimiter=',',dtype = 'int16')
# Recordemos que para crear una matríz los vectores deben de tener la misma longitud
# En el caso contrario, si queremos importar desde un txt en que un vector tenga más elementos que otro
# Obtendremos un error que nos indicara eso
print(data)

[[70 84 93 88  7 35 32 71 27 25]
 [54 11 26 12 55 23 19 42 58 48]
 [18 29 45 10 93 49 17 24 59 75]]


### Enmascaramiento booleano e indexación avanzada 

In [216]:
# Podemos obtener cierta información de manera booleana con ayuda de Numpy
# Por ejemplo si quisieramos saber cual dato en la matríz es mayor a 50 hariamos
data > 50

array([[ True,  True,  True,  True, False, False, False,  True, False,
        False],
       [ True, False, False, False,  True, False, False, False,  True,
        False],
       [False, False, False, False,  True, False, False, False,  True,
         True]])

In [220]:
# Tambien podriamos obtener de forma directa los elementos que cumplen una condición
# Para ello pondremos el nombre de la matríz y en el indice pondremos la condición, de la siguiente forma
mayores_a_50 = data[data>50]
mayores_a_50

array([70, 84, 93, 88, 71, 54, 55, 58, 93, 59, 75], dtype=int16)

In [221]:
# En numpy se permite indexar con listas, de manera tal que podemos obtener ciertos elementos de esta forma
# Supongamos que queremos obtener el primero y el último de los mayores a 50
mayores_a_50[[0,-1]] # Nos devolvera el elemento de indice 0(primero) y el elemento de indice -1 (último)

array([70, 75], dtype=int16)

In [222]:
# Tambien podriamos comprobar si existen mayores a 50 entre las filas, lo haríamos de esta forma
np.any(data > 50,axis = 0) # Esto comprueba si alguno en la columna tiene un valor mayor que 50

array([ True,  True,  True,  True,  True, False, False,  True,  True,
        True])

In [228]:
# Tambíen podriamos comprobar si todos los elementos de la columna 
# cumplen con esa condición, para ello cambiamos any por all
np.all(data > 25, axis = 0) 
# Cambiamos la condición para 25 para que haya algunos true, puedes comprobarlo tú mismo. Experimenta.
# Podrías realizar las mismas pruebas para las filas, solo tendrías que cambiar axis = 0 por axis = 1.

array([False, False,  True, False, False, False, False, False,  True,
       False])

In [244]:
# Otra cosa que podrías cambiar para probar son las condiciones, podrias armar condiciones complejas
# Por ejemplo crearemos una función que obtenga los mayores a 50 y menores de 70 más los menores de 20
(((50 < data) & (data < 70)) + (data < 20))

array([[False, False, False, False,  True, False, False, False, False,
        False],
       [ True,  True, False,  True,  True, False,  True, False,  True,
        False],
       [ True, False, False,  True, False, False,  True, False,  True,
        False]])

In [246]:
# Si quisieramos obtener como true todos los que no cumplan una condición, deberiamos de cambiar la condición
# Pero una forma más sencilla es negar esa condición, de forma que invertiriamos los resultados, tal que así
(~((50 < data) & (data < 70)) + (data < 20)) 
# Tan solo agregamos el simbolo "~" delante de la proposición a negar

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False,  True,  True,  True, False,  True,  True,  True, False,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True]])

### Ejercicio Número 2 : Utilice indexación para llegar al resultado

In [248]:
# Supongamos que tenemos una matríz del 1 al 30 de 6 filas y 5 columnas, de la siguiente forma
matriz = np.arange(1,31)
matriz = matriz.reshape(6,5)
print(matriz)
# Entonces queremos obtener con indexación, la matríz [[11,12],[16,17]]
# ¿Cómo lo harías? Trata de resolverlo tu solo y luego mira la resolución

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [254]:
vect1 = matriz[((matriz > 10) & (matriz < 13))] # Obtenemos los que cumplan con la condición >10 y <13
vect2 = matriz[((matriz > 15) & (matriz < 18))] # Obtenemos los que cumplan con la condición >15 y <18
print(vect1)
print(vect2,"\n")
respuesta = np.vstack([vect1,vect2]) # Armamos la matríz a partir de los vectores obtenidos
print(respuesta)

[11 12]
[16 17] 

[[11 12]
 [16 17]]


###### Esto ha sido todo, para más información te dejaré los links a la página oficial de Numpy en el repo oficial
##### Espero te haya gustado, si es así hazmelo saber por mis redes, las cuales tendrás disponibles tambien en el repo, saludos !